### ISSUE TITLE
CI/CD design

### ISSUE THREAD

**Issue by oo1463** [oo1463/FaceBattle_image_backend#11]
1. github main branch merged -> docker hub build image -> aws ec2 container change

2.  github main branch merged -> aws ec2 git pull main branch -> ec2 docker image build -> ec2 container change -> push the image to docker hub 

what is the best CI / CD process?

**Comment by yoonseopshin** [comment]
1번이 더 짧아 보이는데 더 좋지 않을까 싶네요
